### ISSUE TITLE
Build 1.3.3 for all numpy versions from 1.11

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/kwant-feedstock#53]
Currently in the [`meta.yaml`](https://github.com/conda-forge/kwant-feedstock/blob/master/recipe/meta.yaml) we have 
```
requirements:
  host:
    - numpy >=1.11
    - ...
  run:
    - {{ pin_compatible('numpy') }}
    - ...
```
However this results in a build that **only** works with `numpy=1.15`. We should change this to it to work with all `numpy` versions from `1.11`.

I've asked this on [Gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=5bbf1529271506518df1a8c3).
